name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  VITEST_SEGFAULT_RETRY: 3

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm exec eslint .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          build: true

      - name: Typecheck
        run: pnpm run typecheck

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18, 20]
        include:
          - os: macos-latest
            node-version: 20
          - os: windows-latest
            node-version: 20
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
          build: true
          browser-testing-frameworks: playwright

      - name: Test
        run: pnpm run test:ci

      - name: Test No Threads
        run: pnpm run test:ci:no-threads

      - name: Test Vm Threads
        run: pnpm run test:ci:vm-threads

  test-ui:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          browser-testing-frameworks: cypress

      - name: Test UI
        run: pnpm run ui:test

  test-browser:
    name: test-browser (${{ matrix.os }}, ${{ matrix.browser[0] }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        browser: [[chrome, chromium], [firefox, firefox], [edge, webkit]]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          build: true
          browser-testing-frameworks: playwright

      - name: Test Browser (webdriverio)
        run: pnpm run test:browser:webdriverio
        env:
          BROWSER: ${{ matrix.browser[0] }}

      - name: Test Browser (playwright)
        run: pnpm run test:browser:playwright
        env:
          BROWSER: ${{ matrix.browser[1] }}
