name: Issue Close Require

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    if: github.repository == 'vitest-dev/vitest'
    steps:
      - name: need reproduction
        uses: actions-cool/issues-helper@v3
        with:
          actions: close-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: need reproduction
          inactive-day: 3
